#REQUIREMENTS#

# The essentials
- pandas==1.4.0
- numpy==1.21.5
- matplotlib==3.5.1
- seaborn==0.11.2
- json==2.0.9
- pickle==4.1
- googlemaps==4.5.3
- folium==0.12.1
- geopy==2.2.0
- scikit-learn==1.0
- ipywidgets==7.6.5

# Wrangling and Processing
- tqdm==4.62.3
- cleantext==1.1.3

# Feature Engineering: Standardising Scaling, Regularizing and Transforming
- scikit-learn==1.0
- itertools==0.0
- simpleImputer==0.0.0
- spacy==3.3.0
- statsmodels==0.13.1

# NLP
- cleantext==1.1.3
- spacy==3.3.0
- scikit-learn==1.0

# Column Transformer, Pipeline, Modeling
- scikit-learn==1.0
- lightgbm==3.3.2
- xgboost==1.5.0

# Time Series Modeling
- statsmodels==0.13.1
- pmdarima==1.8.3

# Hyperparameter Tuning
- scikit-learn==1.0

# Model Evaluation
- scikit-learn==1.0
- statsmodels==0.13.1